// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blug/internal/data/ent/article"
	"blug/internal/data/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ArticleUpdate is the builder for updating Article entities.
type ArticleUpdate struct {
	config
	hooks    []Hook
	mutation *ArticleMutation
}

// Where appends a list predicates to the ArticleUpdate builder.
func (au *ArticleUpdate) Where(ps ...predicate.Article) *ArticleUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetTitle sets the "title" field.
func (au *ArticleUpdate) SetTitle(s string) *ArticleUpdate {
	au.mutation.SetTitle(s)
	return au
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableTitle(s *string) *ArticleUpdate {
	if s != nil {
		au.SetTitle(*s)
	}
	return au
}

// SetDesc sets the "desc" field.
func (au *ArticleUpdate) SetDesc(s string) *ArticleUpdate {
	au.mutation.SetDesc(s)
	return au
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableDesc(s *string) *ArticleUpdate {
	if s != nil {
		au.SetDesc(*s)
	}
	return au
}

// SetCategory sets the "category" field.
func (au *ArticleUpdate) SetCategory(s string) *ArticleUpdate {
	au.mutation.SetCategory(s)
	return au
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableCategory(s *string) *ArticleUpdate {
	if s != nil {
		au.SetCategory(*s)
	}
	return au
}

// SetTags sets the "tags" field.
func (au *ArticleUpdate) SetTags(s string) *ArticleUpdate {
	au.mutation.SetTags(s)
	return au
}

// SetNillableTags sets the "tags" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableTags(s *string) *ArticleUpdate {
	if s != nil {
		au.SetTags(*s)
	}
	return au
}

// SetURL sets the "url" field.
func (au *ArticleUpdate) SetURL(s string) *ArticleUpdate {
	au.mutation.SetURL(s)
	return au
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableURL(s *string) *ArticleUpdate {
	if s != nil {
		au.SetURL(*s)
	}
	return au
}

// SetIsShow sets the "is_show" field.
func (au *ArticleUpdate) SetIsShow(b bool) *ArticleUpdate {
	au.mutation.SetIsShow(b)
	return au
}

// SetNillableIsShow sets the "is_show" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableIsShow(b *bool) *ArticleUpdate {
	if b != nil {
		au.SetIsShow(*b)
	}
	return au
}

// SetContent sets the "content" field.
func (au *ArticleUpdate) SetContent(s string) *ArticleUpdate {
	au.mutation.SetContent(s)
	return au
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableContent(s *string) *ArticleUpdate {
	if s != nil {
		au.SetContent(*s)
	}
	return au
}

// Mutation returns the ArticleMutation object of the builder.
func (au *ArticleUpdate) Mutation() *ArticleMutation {
	return au.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *ArticleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *ArticleUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *ArticleUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *ArticleUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

func (au *ArticleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(article.Table, article.Columns, sqlgraph.NewFieldSpec(article.FieldID, field.TypeUUID))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Title(); ok {
		_spec.SetField(article.FieldTitle, field.TypeString, value)
	}
	if value, ok := au.mutation.Desc(); ok {
		_spec.SetField(article.FieldDesc, field.TypeString, value)
	}
	if value, ok := au.mutation.Category(); ok {
		_spec.SetField(article.FieldCategory, field.TypeString, value)
	}
	if value, ok := au.mutation.Tags(); ok {
		_spec.SetField(article.FieldTags, field.TypeString, value)
	}
	if value, ok := au.mutation.URL(); ok {
		_spec.SetField(article.FieldURL, field.TypeString, value)
	}
	if value, ok := au.mutation.IsShow(); ok {
		_spec.SetField(article.FieldIsShow, field.TypeBool, value)
	}
	if value, ok := au.mutation.Content(); ok {
		_spec.SetField(article.FieldContent, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{article.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// ArticleUpdateOne is the builder for updating a single Article entity.
type ArticleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ArticleMutation
}

// SetTitle sets the "title" field.
func (auo *ArticleUpdateOne) SetTitle(s string) *ArticleUpdateOne {
	auo.mutation.SetTitle(s)
	return auo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableTitle(s *string) *ArticleUpdateOne {
	if s != nil {
		auo.SetTitle(*s)
	}
	return auo
}

// SetDesc sets the "desc" field.
func (auo *ArticleUpdateOne) SetDesc(s string) *ArticleUpdateOne {
	auo.mutation.SetDesc(s)
	return auo
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableDesc(s *string) *ArticleUpdateOne {
	if s != nil {
		auo.SetDesc(*s)
	}
	return auo
}

// SetCategory sets the "category" field.
func (auo *ArticleUpdateOne) SetCategory(s string) *ArticleUpdateOne {
	auo.mutation.SetCategory(s)
	return auo
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableCategory(s *string) *ArticleUpdateOne {
	if s != nil {
		auo.SetCategory(*s)
	}
	return auo
}

// SetTags sets the "tags" field.
func (auo *ArticleUpdateOne) SetTags(s string) *ArticleUpdateOne {
	auo.mutation.SetTags(s)
	return auo
}

// SetNillableTags sets the "tags" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableTags(s *string) *ArticleUpdateOne {
	if s != nil {
		auo.SetTags(*s)
	}
	return auo
}

// SetURL sets the "url" field.
func (auo *ArticleUpdateOne) SetURL(s string) *ArticleUpdateOne {
	auo.mutation.SetURL(s)
	return auo
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableURL(s *string) *ArticleUpdateOne {
	if s != nil {
		auo.SetURL(*s)
	}
	return auo
}

// SetIsShow sets the "is_show" field.
func (auo *ArticleUpdateOne) SetIsShow(b bool) *ArticleUpdateOne {
	auo.mutation.SetIsShow(b)
	return auo
}

// SetNillableIsShow sets the "is_show" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableIsShow(b *bool) *ArticleUpdateOne {
	if b != nil {
		auo.SetIsShow(*b)
	}
	return auo
}

// SetContent sets the "content" field.
func (auo *ArticleUpdateOne) SetContent(s string) *ArticleUpdateOne {
	auo.mutation.SetContent(s)
	return auo
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableContent(s *string) *ArticleUpdateOne {
	if s != nil {
		auo.SetContent(*s)
	}
	return auo
}

// Mutation returns the ArticleMutation object of the builder.
func (auo *ArticleUpdateOne) Mutation() *ArticleMutation {
	return auo.mutation
}

// Where appends a list predicates to the ArticleUpdate builder.
func (auo *ArticleUpdateOne) Where(ps ...predicate.Article) *ArticleUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *ArticleUpdateOne) Select(field string, fields ...string) *ArticleUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Article entity.
func (auo *ArticleUpdateOne) Save(ctx context.Context) (*Article, error) {
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *ArticleUpdateOne) SaveX(ctx context.Context) *Article {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *ArticleUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *ArticleUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (auo *ArticleUpdateOne) sqlSave(ctx context.Context) (_node *Article, err error) {
	_spec := sqlgraph.NewUpdateSpec(article.Table, article.Columns, sqlgraph.NewFieldSpec(article.FieldID, field.TypeUUID))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Article.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, article.FieldID)
		for _, f := range fields {
			if !article.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != article.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Title(); ok {
		_spec.SetField(article.FieldTitle, field.TypeString, value)
	}
	if value, ok := auo.mutation.Desc(); ok {
		_spec.SetField(article.FieldDesc, field.TypeString, value)
	}
	if value, ok := auo.mutation.Category(); ok {
		_spec.SetField(article.FieldCategory, field.TypeString, value)
	}
	if value, ok := auo.mutation.Tags(); ok {
		_spec.SetField(article.FieldTags, field.TypeString, value)
	}
	if value, ok := auo.mutation.URL(); ok {
		_spec.SetField(article.FieldURL, field.TypeString, value)
	}
	if value, ok := auo.mutation.IsShow(); ok {
		_spec.SetField(article.FieldIsShow, field.TypeBool, value)
	}
	if value, ok := auo.mutation.Content(); ok {
		_spec.SetField(article.FieldContent, field.TypeString, value)
	}
	_node = &Article{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{article.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
