// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blug/internal/data/ent/friend"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// FriendCreate is the builder for creating a Friend entity.
type FriendCreate struct {
	config
	mutation *FriendMutation
	hooks    []Hook
}

// SetTitle sets the "Title" field.
func (fc *FriendCreate) SetTitle(s string) *FriendCreate {
	fc.mutation.SetTitle(s)
	return fc
}

// SetNillableTitle sets the "Title" field if the given value is not nil.
func (fc *FriendCreate) SetNillableTitle(s *string) *FriendCreate {
	if s != nil {
		fc.SetTitle(*s)
	}
	return fc
}

// SetDesc sets the "Desc" field.
func (fc *FriendCreate) SetDesc(s string) *FriendCreate {
	fc.mutation.SetDesc(s)
	return fc
}

// SetNillableDesc sets the "Desc" field if the given value is not nil.
func (fc *FriendCreate) SetNillableDesc(s *string) *FriendCreate {
	if s != nil {
		fc.SetDesc(*s)
	}
	return fc
}

// SetLink sets the "Link" field.
func (fc *FriendCreate) SetLink(s string) *FriendCreate {
	fc.mutation.SetLink(s)
	return fc
}

// SetNillableLink sets the "Link" field if the given value is not nil.
func (fc *FriendCreate) SetNillableLink(s *string) *FriendCreate {
	if s != nil {
		fc.SetLink(*s)
	}
	return fc
}

// SetAvatar sets the "Avatar" field.
func (fc *FriendCreate) SetAvatar(s string) *FriendCreate {
	fc.mutation.SetAvatar(s)
	return fc
}

// SetNillableAvatar sets the "Avatar" field if the given value is not nil.
func (fc *FriendCreate) SetNillableAvatar(s *string) *FriendCreate {
	if s != nil {
		fc.SetAvatar(*s)
	}
	return fc
}

// SetCreateTime sets the "create_time" field.
func (fc *FriendCreate) SetCreateTime(t time.Time) *FriendCreate {
	fc.mutation.SetCreateTime(t)
	return fc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (fc *FriendCreate) SetNillableCreateTime(t *time.Time) *FriendCreate {
	if t != nil {
		fc.SetCreateTime(*t)
	}
	return fc
}

// SetID sets the "id" field.
func (fc *FriendCreate) SetID(u uuid.UUID) *FriendCreate {
	fc.mutation.SetID(u)
	return fc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (fc *FriendCreate) SetNillableID(u *uuid.UUID) *FriendCreate {
	if u != nil {
		fc.SetID(*u)
	}
	return fc
}

// Mutation returns the FriendMutation object of the builder.
func (fc *FriendCreate) Mutation() *FriendMutation {
	return fc.mutation
}

// Save creates the Friend in the database.
func (fc *FriendCreate) Save(ctx context.Context) (*Friend, error) {
	fc.defaults()
	return withHooks(ctx, fc.sqlSave, fc.mutation, fc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (fc *FriendCreate) SaveX(ctx context.Context) *Friend {
	v, err := fc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fc *FriendCreate) Exec(ctx context.Context) error {
	_, err := fc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fc *FriendCreate) ExecX(ctx context.Context) {
	if err := fc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fc *FriendCreate) defaults() {
	if _, ok := fc.mutation.Title(); !ok {
		v := friend.DefaultTitle
		fc.mutation.SetTitle(v)
	}
	if _, ok := fc.mutation.Desc(); !ok {
		v := friend.DefaultDesc
		fc.mutation.SetDesc(v)
	}
	if _, ok := fc.mutation.Link(); !ok {
		v := friend.DefaultLink
		fc.mutation.SetLink(v)
	}
	if _, ok := fc.mutation.Avatar(); !ok {
		v := friend.DefaultAvatar
		fc.mutation.SetAvatar(v)
	}
	if _, ok := fc.mutation.CreateTime(); !ok {
		v := friend.DefaultCreateTime()
		fc.mutation.SetCreateTime(v)
	}
	if _, ok := fc.mutation.ID(); !ok {
		v := friend.DefaultID()
		fc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fc *FriendCreate) check() error {
	if _, ok := fc.mutation.Title(); !ok {
		return &ValidationError{Name: "Title", err: errors.New(`ent: missing required field "Friend.Title"`)}
	}
	if _, ok := fc.mutation.Desc(); !ok {
		return &ValidationError{Name: "Desc", err: errors.New(`ent: missing required field "Friend.Desc"`)}
	}
	if _, ok := fc.mutation.Link(); !ok {
		return &ValidationError{Name: "Link", err: errors.New(`ent: missing required field "Friend.Link"`)}
	}
	if _, ok := fc.mutation.Avatar(); !ok {
		return &ValidationError{Name: "Avatar", err: errors.New(`ent: missing required field "Friend.Avatar"`)}
	}
	if _, ok := fc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Friend.create_time"`)}
	}
	return nil
}

func (fc *FriendCreate) sqlSave(ctx context.Context) (*Friend, error) {
	if err := fc.check(); err != nil {
		return nil, err
	}
	_node, _spec := fc.createSpec()
	if err := sqlgraph.CreateNode(ctx, fc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	fc.mutation.id = &_node.ID
	fc.mutation.done = true
	return _node, nil
}

func (fc *FriendCreate) createSpec() (*Friend, *sqlgraph.CreateSpec) {
	var (
		_node = &Friend{config: fc.config}
		_spec = sqlgraph.NewCreateSpec(friend.Table, sqlgraph.NewFieldSpec(friend.FieldID, field.TypeUUID))
	)
	if id, ok := fc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := fc.mutation.Title(); ok {
		_spec.SetField(friend.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := fc.mutation.Desc(); ok {
		_spec.SetField(friend.FieldDesc, field.TypeString, value)
		_node.Desc = value
	}
	if value, ok := fc.mutation.Link(); ok {
		_spec.SetField(friend.FieldLink, field.TypeString, value)
		_node.Link = value
	}
	if value, ok := fc.mutation.Avatar(); ok {
		_spec.SetField(friend.FieldAvatar, field.TypeString, value)
		_node.Avatar = value
	}
	if value, ok := fc.mutation.CreateTime(); ok {
		_spec.SetField(friend.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	return _node, _spec
}

// FriendCreateBulk is the builder for creating many Friend entities in bulk.
type FriendCreateBulk struct {
	config
	err      error
	builders []*FriendCreate
}

// Save creates the Friend entities in the database.
func (fcb *FriendCreateBulk) Save(ctx context.Context) ([]*Friend, error) {
	if fcb.err != nil {
		return nil, fcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(fcb.builders))
	nodes := make([]*Friend, len(fcb.builders))
	mutators := make([]Mutator, len(fcb.builders))
	for i := range fcb.builders {
		func(i int, root context.Context) {
			builder := fcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FriendMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, fcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, fcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, fcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (fcb *FriendCreateBulk) SaveX(ctx context.Context) []*Friend {
	v, err := fcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fcb *FriendCreateBulk) Exec(ctx context.Context) error {
	_, err := fcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fcb *FriendCreateBulk) ExecX(ctx context.Context) {
	if err := fcb.Exec(ctx); err != nil {
		panic(err)
	}
}
