// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blug/internal/data/ent/predicate"
	"blug/internal/data/ent/task"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskUpdate is the builder for updating Task entities.
type TaskUpdate struct {
	config
	hooks    []Hook
	mutation *TaskMutation
}

// Where appends a list predicates to the TaskUpdate builder.
func (tu *TaskUpdate) Where(ps ...predicate.Task) *TaskUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetTaskID sets the "task_id" field.
func (tu *TaskUpdate) SetTaskID(s string) *TaskUpdate {
	tu.mutation.SetTaskID(s)
	return tu
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableTaskID(s *string) *TaskUpdate {
	if s != nil {
		tu.SetTaskID(*s)
	}
	return tu
}

// SetTaskName sets the "task_name" field.
func (tu *TaskUpdate) SetTaskName(s string) *TaskUpdate {
	tu.mutation.SetTaskName(s)
	return tu
}

// SetNillableTaskName sets the "task_name" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableTaskName(s *string) *TaskUpdate {
	if s != nil {
		tu.SetTaskName(*s)
	}
	return tu
}

// SetTaskType sets the "task_type" field.
func (tu *TaskUpdate) SetTaskType(s string) *TaskUpdate {
	tu.mutation.SetTaskType(s)
	return tu
}

// SetNillableTaskType sets the "task_type" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableTaskType(s *string) *TaskUpdate {
	if s != nil {
		tu.SetTaskType(*s)
	}
	return tu
}

// SetStatus sets the "status" field.
func (tu *TaskUpdate) SetStatus(s string) *TaskUpdate {
	tu.mutation.SetStatus(s)
	return tu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableStatus(s *string) *TaskUpdate {
	if s != nil {
		tu.SetStatus(*s)
	}
	return tu
}

// SetReason sets the "reason" field.
func (tu *TaskUpdate) SetReason(s string) *TaskUpdate {
	tu.mutation.SetReason(s)
	return tu
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableReason(s *string) *TaskUpdate {
	if s != nil {
		tu.SetReason(*s)
	}
	return tu
}

// SetFinishTime sets the "finish_time" field.
func (tu *TaskUpdate) SetFinishTime(s string) *TaskUpdate {
	tu.mutation.SetFinishTime(s)
	return tu
}

// SetNillableFinishTime sets the "finish_time" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableFinishTime(s *string) *TaskUpdate {
	if s != nil {
		tu.SetFinishTime(*s)
	}
	return tu
}

// SetRetry sets the "retry" field.
func (tu *TaskUpdate) SetRetry(i int) *TaskUpdate {
	tu.mutation.ResetRetry()
	tu.mutation.SetRetry(i)
	return tu
}

// SetNillableRetry sets the "retry" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableRetry(i *int) *TaskUpdate {
	if i != nil {
		tu.SetRetry(*i)
	}
	return tu
}

// AddRetry adds i to the "retry" field.
func (tu *TaskUpdate) AddRetry(i int) *TaskUpdate {
	tu.mutation.AddRetry(i)
	return tu
}

// Mutation returns the TaskMutation object of the builder.
func (tu *TaskUpdate) Mutation() *TaskMutation {
	return tu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TaskUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TaskUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TaskUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TaskUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tu *TaskUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.TaskID(); ok {
		_spec.SetField(task.FieldTaskID, field.TypeString, value)
	}
	if value, ok := tu.mutation.TaskName(); ok {
		_spec.SetField(task.FieldTaskName, field.TypeString, value)
	}
	if value, ok := tu.mutation.TaskType(); ok {
		_spec.SetField(task.FieldTaskType, field.TypeString, value)
	}
	if value, ok := tu.mutation.Status(); ok {
		_spec.SetField(task.FieldStatus, field.TypeString, value)
	}
	if value, ok := tu.mutation.Reason(); ok {
		_spec.SetField(task.FieldReason, field.TypeString, value)
	}
	if value, ok := tu.mutation.FinishTime(); ok {
		_spec.SetField(task.FieldFinishTime, field.TypeString, value)
	}
	if value, ok := tu.mutation.Retry(); ok {
		_spec.SetField(task.FieldRetry, field.TypeInt, value)
	}
	if value, ok := tu.mutation.AddedRetry(); ok {
		_spec.AddField(task.FieldRetry, field.TypeInt, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TaskUpdateOne is the builder for updating a single Task entity.
type TaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskMutation
}

// SetTaskID sets the "task_id" field.
func (tuo *TaskUpdateOne) SetTaskID(s string) *TaskUpdateOne {
	tuo.mutation.SetTaskID(s)
	return tuo
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableTaskID(s *string) *TaskUpdateOne {
	if s != nil {
		tuo.SetTaskID(*s)
	}
	return tuo
}

// SetTaskName sets the "task_name" field.
func (tuo *TaskUpdateOne) SetTaskName(s string) *TaskUpdateOne {
	tuo.mutation.SetTaskName(s)
	return tuo
}

// SetNillableTaskName sets the "task_name" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableTaskName(s *string) *TaskUpdateOne {
	if s != nil {
		tuo.SetTaskName(*s)
	}
	return tuo
}

// SetTaskType sets the "task_type" field.
func (tuo *TaskUpdateOne) SetTaskType(s string) *TaskUpdateOne {
	tuo.mutation.SetTaskType(s)
	return tuo
}

// SetNillableTaskType sets the "task_type" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableTaskType(s *string) *TaskUpdateOne {
	if s != nil {
		tuo.SetTaskType(*s)
	}
	return tuo
}

// SetStatus sets the "status" field.
func (tuo *TaskUpdateOne) SetStatus(s string) *TaskUpdateOne {
	tuo.mutation.SetStatus(s)
	return tuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableStatus(s *string) *TaskUpdateOne {
	if s != nil {
		tuo.SetStatus(*s)
	}
	return tuo
}

// SetReason sets the "reason" field.
func (tuo *TaskUpdateOne) SetReason(s string) *TaskUpdateOne {
	tuo.mutation.SetReason(s)
	return tuo
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableReason(s *string) *TaskUpdateOne {
	if s != nil {
		tuo.SetReason(*s)
	}
	return tuo
}

// SetFinishTime sets the "finish_time" field.
func (tuo *TaskUpdateOne) SetFinishTime(s string) *TaskUpdateOne {
	tuo.mutation.SetFinishTime(s)
	return tuo
}

// SetNillableFinishTime sets the "finish_time" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableFinishTime(s *string) *TaskUpdateOne {
	if s != nil {
		tuo.SetFinishTime(*s)
	}
	return tuo
}

// SetRetry sets the "retry" field.
func (tuo *TaskUpdateOne) SetRetry(i int) *TaskUpdateOne {
	tuo.mutation.ResetRetry()
	tuo.mutation.SetRetry(i)
	return tuo
}

// SetNillableRetry sets the "retry" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableRetry(i *int) *TaskUpdateOne {
	if i != nil {
		tuo.SetRetry(*i)
	}
	return tuo
}

// AddRetry adds i to the "retry" field.
func (tuo *TaskUpdateOne) AddRetry(i int) *TaskUpdateOne {
	tuo.mutation.AddRetry(i)
	return tuo
}

// Mutation returns the TaskMutation object of the builder.
func (tuo *TaskUpdateOne) Mutation() *TaskMutation {
	return tuo.mutation
}

// Where appends a list predicates to the TaskUpdate builder.
func (tuo *TaskUpdateOne) Where(ps ...predicate.Task) *TaskUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TaskUpdateOne) Select(field string, fields ...string) *TaskUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Task entity.
func (tuo *TaskUpdateOne) Save(ctx context.Context) (*Task, error) {
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TaskUpdateOne) SaveX(ctx context.Context) *Task {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TaskUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TaskUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tuo *TaskUpdateOne) sqlSave(ctx context.Context) (_node *Task, err error) {
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Task.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, task.FieldID)
		for _, f := range fields {
			if !task.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != task.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.TaskID(); ok {
		_spec.SetField(task.FieldTaskID, field.TypeString, value)
	}
	if value, ok := tuo.mutation.TaskName(); ok {
		_spec.SetField(task.FieldTaskName, field.TypeString, value)
	}
	if value, ok := tuo.mutation.TaskType(); ok {
		_spec.SetField(task.FieldTaskType, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Status(); ok {
		_spec.SetField(task.FieldStatus, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Reason(); ok {
		_spec.SetField(task.FieldReason, field.TypeString, value)
	}
	if value, ok := tuo.mutation.FinishTime(); ok {
		_spec.SetField(task.FieldFinishTime, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Retry(); ok {
		_spec.SetField(task.FieldRetry, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.AddedRetry(); ok {
		_spec.AddField(task.FieldRetry, field.TypeInt, value)
	}
	_node = &Task{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
