// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blug/internal/data/ent/task"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskCreate is the builder for creating a Task entity.
type TaskCreate struct {
	config
	mutation *TaskMutation
	hooks    []Hook
}

// SetTaskID sets the "task_id" field.
func (tc *TaskCreate) SetTaskID(s string) *TaskCreate {
	tc.mutation.SetTaskID(s)
	return tc
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (tc *TaskCreate) SetNillableTaskID(s *string) *TaskCreate {
	if s != nil {
		tc.SetTaskID(*s)
	}
	return tc
}

// SetTaskName sets the "task_name" field.
func (tc *TaskCreate) SetTaskName(s string) *TaskCreate {
	tc.mutation.SetTaskName(s)
	return tc
}

// SetNillableTaskName sets the "task_name" field if the given value is not nil.
func (tc *TaskCreate) SetNillableTaskName(s *string) *TaskCreate {
	if s != nil {
		tc.SetTaskName(*s)
	}
	return tc
}

// SetTaskType sets the "task_type" field.
func (tc *TaskCreate) SetTaskType(s string) *TaskCreate {
	tc.mutation.SetTaskType(s)
	return tc
}

// SetNillableTaskType sets the "task_type" field if the given value is not nil.
func (tc *TaskCreate) SetNillableTaskType(s *string) *TaskCreate {
	if s != nil {
		tc.SetTaskType(*s)
	}
	return tc
}

// SetStatus sets the "status" field.
func (tc *TaskCreate) SetStatus(s string) *TaskCreate {
	tc.mutation.SetStatus(s)
	return tc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (tc *TaskCreate) SetNillableStatus(s *string) *TaskCreate {
	if s != nil {
		tc.SetStatus(*s)
	}
	return tc
}

// SetReason sets the "reason" field.
func (tc *TaskCreate) SetReason(s string) *TaskCreate {
	tc.mutation.SetReason(s)
	return tc
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (tc *TaskCreate) SetNillableReason(s *string) *TaskCreate {
	if s != nil {
		tc.SetReason(*s)
	}
	return tc
}

// SetCreateTime sets the "create_time" field.
func (tc *TaskCreate) SetCreateTime(s string) *TaskCreate {
	tc.mutation.SetCreateTime(s)
	return tc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (tc *TaskCreate) SetNillableCreateTime(s *string) *TaskCreate {
	if s != nil {
		tc.SetCreateTime(*s)
	}
	return tc
}

// SetFinishTime sets the "finish_time" field.
func (tc *TaskCreate) SetFinishTime(s string) *TaskCreate {
	tc.mutation.SetFinishTime(s)
	return tc
}

// SetNillableFinishTime sets the "finish_time" field if the given value is not nil.
func (tc *TaskCreate) SetNillableFinishTime(s *string) *TaskCreate {
	if s != nil {
		tc.SetFinishTime(*s)
	}
	return tc
}

// Mutation returns the TaskMutation object of the builder.
func (tc *TaskCreate) Mutation() *TaskMutation {
	return tc.mutation
}

// Save creates the Task in the database.
func (tc *TaskCreate) Save(ctx context.Context) (*Task, error) {
	tc.defaults()
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TaskCreate) SaveX(ctx context.Context) *Task {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TaskCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TaskCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tc *TaskCreate) defaults() {
	if _, ok := tc.mutation.TaskID(); !ok {
		v := task.DefaultTaskID
		tc.mutation.SetTaskID(v)
	}
	if _, ok := tc.mutation.TaskName(); !ok {
		v := task.DefaultTaskName
		tc.mutation.SetTaskName(v)
	}
	if _, ok := tc.mutation.TaskType(); !ok {
		v := task.DefaultTaskType
		tc.mutation.SetTaskType(v)
	}
	if _, ok := tc.mutation.Status(); !ok {
		v := task.DefaultStatus
		tc.mutation.SetStatus(v)
	}
	if _, ok := tc.mutation.Reason(); !ok {
		v := task.DefaultReason
		tc.mutation.SetReason(v)
	}
	if _, ok := tc.mutation.CreateTime(); !ok {
		v := task.DefaultCreateTime
		tc.mutation.SetCreateTime(v)
	}
	if _, ok := tc.mutation.FinishTime(); !ok {
		v := task.DefaultFinishTime
		tc.mutation.SetFinishTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TaskCreate) check() error {
	if _, ok := tc.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "Task.task_id"`)}
	}
	if _, ok := tc.mutation.TaskName(); !ok {
		return &ValidationError{Name: "task_name", err: errors.New(`ent: missing required field "Task.task_name"`)}
	}
	if _, ok := tc.mutation.TaskType(); !ok {
		return &ValidationError{Name: "task_type", err: errors.New(`ent: missing required field "Task.task_type"`)}
	}
	if _, ok := tc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Task.status"`)}
	}
	if _, ok := tc.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "Task.reason"`)}
	}
	if _, ok := tc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Task.create_time"`)}
	}
	if _, ok := tc.mutation.FinishTime(); !ok {
		return &ValidationError{Name: "finish_time", err: errors.New(`ent: missing required field "Task.finish_time"`)}
	}
	return nil
}

func (tc *TaskCreate) sqlSave(ctx context.Context) (*Task, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *TaskCreate) createSpec() (*Task, *sqlgraph.CreateSpec) {
	var (
		_node = &Task{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(task.Table, sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt))
	)
	if value, ok := tc.mutation.TaskID(); ok {
		_spec.SetField(task.FieldTaskID, field.TypeString, value)
		_node.TaskID = value
	}
	if value, ok := tc.mutation.TaskName(); ok {
		_spec.SetField(task.FieldTaskName, field.TypeString, value)
		_node.TaskName = value
	}
	if value, ok := tc.mutation.TaskType(); ok {
		_spec.SetField(task.FieldTaskType, field.TypeString, value)
		_node.TaskType = value
	}
	if value, ok := tc.mutation.Status(); ok {
		_spec.SetField(task.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := tc.mutation.Reason(); ok {
		_spec.SetField(task.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := tc.mutation.CreateTime(); ok {
		_spec.SetField(task.FieldCreateTime, field.TypeString, value)
		_node.CreateTime = value
	}
	if value, ok := tc.mutation.FinishTime(); ok {
		_spec.SetField(task.FieldFinishTime, field.TypeString, value)
		_node.FinishTime = value
	}
	return _node, _spec
}

// TaskCreateBulk is the builder for creating many Task entities in bulk.
type TaskCreateBulk struct {
	config
	err      error
	builders []*TaskCreate
}

// Save creates the Task entities in the database.
func (tcb *TaskCreateBulk) Save(ctx context.Context) ([]*Task, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Task, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TaskCreateBulk) SaveX(ctx context.Context) []*Task {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TaskCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TaskCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
